[package]
name = "chaos"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.2.1"
bevy = { version = "0.15.3", features = ["dynamic_linking"] }
bevy_rapier3d = "0.29.0"
rand = "0.9.0"
rand_chacha = "0.9.0"
